title: Agoric patterns
description: This website introduces 16 patterns for Agoric smart contracts and the seat structure diagram: a diagram which captures the relationship between seats within an Agoric smart contract.
remote_theme: pages-themes/cayman@v0.2.0
url: https://ilyasmercan.github.io/
baseurl: /AgoricPatterns/
